<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0-preview2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0-preview2-2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Gaia\Gaia\Gaia.csproj" />
    <ProjectReference Include="..\..\IconPacks.Avalonia.Aot\src\IconPacks.Avalonia.MaterialDesign\IconPacks.Avalonia.MaterialDesign.csproj" />
    <ProjectReference Include="..\..\Nestor\Nestor.Db\Nestor.Db.csproj" />
    <ProjectReference
      Include="..\Inanna.SourceGenerator\Inanna.SourceGenerator.csproj"
      ReferenceOutputAssembly="false"
      OutputItemType="Analyzer"
    />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Ui\ServiceOfflineStatusView.axaml.cs">
      <DependentUpon>ServiceOfflineStatusView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
