using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Inanna.SourceGenerator;

[Generator]
public class EditNotifyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
           .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax classDeclaration
                 && classDeclaration.AttributeLists
                       .SelectMany(x => x.Attributes)
                       .Any(x => x.Name.ToString() == "EditNotify"),
                static (context, _) => (ClassDeclarationSyntax)context.Node)
           .Collect();

        var combine = context.CompilationProvider.Combine(provider);

        context.RegisterSourceOutput(combine, (spc, obj) =>
        {
            var (compilation, list) = obj;

            foreach (var source in list)
            {
                var properties = source.Members.OfType<PropertyDeclarationSyntax>().ToArray().AsSpan();
                var stringBuilder = new StringBuilder();
                var viewStringBuilder = new StringBuilder();
                viewStringBuilder.AppendLine("/* View");
                viewStringBuilder.AppendLine("<UserControl xmlns=\"https://github.com/avaloniaui\"");
                viewStringBuilder.AppendLine("             xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"");

                viewStringBuilder.AppendLine(
                    "             xmlns:d=\"http://schemas.microsoft.com/expression/blend/2008\"");

                viewStringBuilder.AppendLine(
                    "             xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\"");

                viewStringBuilder.AppendLine($"             xmlns:vm=\"clr-namespace:{source.GetNamespace()}\"");

                viewStringBuilder.AppendLine(
                    "             mc:Ignorable=\"d\" d:DesignWidth=\"800\" d:DesignHeight=\"450\"");

                viewStringBuilder.AppendLine($"             x:Class=\"Inanna.Views.{source.GetName().Substring(
                    0, source.GetName().Length - 5)}\"");

                viewStringBuilder.AppendLine($"             x:DataType=\"vm:{source.GetName()}\">");

                viewStringBuilder.AppendLine(
                    "    <ScrollViewer VerticalScrollBarVisibility=\"Auto\" HorizontalScrollBarVisibility=\"Disabled\">");

                viewStringBuilder.AppendLine("    <StackPanel>");
                stringBuilder.AppendLine("// <auto-generated />");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine("#nullable enable");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine($"namespace {source.GetNamespace()};");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine($"public partial class {source.GetName()}");
                stringBuilder.AppendLine("{");

                stringBuilder.AppendLine(
                    $"    protected override void OnPropertyChanged(global::{TypeNames.PropertyChangedEventArgs} e)");

                stringBuilder.AppendLine("    {");
                stringBuilder.AppendLine("            base.OnPropertyChanged(e);");
                stringBuilder.AppendLine("        switch (e.PropertyName)");
                stringBuilder.AppendLine("        {");
                var enumProperties = new List<PropertyDeclarationSyntax>();
                var editProperties = new List<PropertyDeclarationSyntax>();

                foreach (var property in properties)
                {
                    if (!property.AttributeLists.Any())
                    {
                        continue;
                    }

                    if (property.GetName().StartsWith("IsEdit"))
                    {
                        continue;
                    }

                    editProperties.Add(property);
                    stringBuilder.AppendLine($"            case nameof(IsEdit{property.GetName()}):");
                    stringBuilder.AppendLine("            {");
                    stringBuilder.AppendLine("                OnPropertyChanged(nameof(IsEdit));");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("                break;");
                    stringBuilder.AppendLine("            }");
                    stringBuilder.AppendLine($"            case nameof({property.GetName()}):");
                    stringBuilder.AppendLine("            {");
                    stringBuilder.AppendLine($"                IsEdit{property.GetName()} = true;");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("                break;");
                    stringBuilder.AppendLine("            }");
                    var semanticModel = compilation.GetSemanticModel(property.Type.SyntaxTree);
                    var symbolInfo = semanticModel.GetSymbolInfo(property.Type);
                    var symbol = symbolInfo.Symbol;

                    if (symbol is INamedTypeSymbol { TypeKind: TypeKind.Enum, })
                    {
                        enumProperties.Add(property);
                        CreateInputControl(property, true, viewStringBuilder);
                    }
                    else
                    {
                        CreateInputControl(property, false, viewStringBuilder);
                    }
                }

                viewStringBuilder.AppendLine("    </StackPanel>");
                viewStringBuilder.AppendLine("    </ScrollViewer>");
                viewStringBuilder.AppendLine("</UserControl>");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine("        }");
                stringBuilder.AppendLine("    }");

                stringBuilder.AppendLine(
                    $"protected void ResetEdit() {{{string.Join(string.Empty, editProperties.Select(x => $"IsEdit{x.GetName()} = false;"))};}}");

                stringBuilder.AppendLine(
                    $"public bool IsEdit => {string.Join(" || ", editProperties.Select(x => $"IsEdit{x.GetName()}"))};");

                foreach (var property in enumProperties)
                {
                    stringBuilder.AppendLine();

                    stringBuilder.AppendLine(
                        $"    public global::{TypeNames.AvaloniaList}<{property.Type.GetFullName(compilation)}> {property.GetName()}s {{ get; }} = new(Enum.GetValues<{property.Type.GetFullName(compilation)}>());");
                }

                stringBuilder.AppendLine("}");
                viewStringBuilder.AppendLine("*/");
                stringBuilder.AppendLine(viewStringBuilder.ToString());
                var text = stringBuilder.ToString();
                spc.AddSource($"EditNotify.{source.GetName()}.g.cs", text);
            }
        });
    }

    private void CreateInputControl(PropertyDeclarationSyntax property, bool isEnum, StringBuilder stringBuilder)
    {
        if (isEnum)
        {
            stringBuilder.AppendLine("        <StackPanel>");
            stringBuilder.AppendLine($"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

            stringBuilder.AppendLine(
                $"            <ComboBox SelectedItem=\"{{Binding {property.GetName()}}}\" ItemsSource=\"{{Binding {property.GetName()}s}}\" />");

            stringBuilder.AppendLine("        </StackPanel>");

            return;
        }

        switch (property.Type.ToString())
        {
            case "bool":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine($"            <CheckBox IsChecked=\"{{Binding {property.GetName()}}}\"/>");
                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "byte":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "ushort":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "uint":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "ulong":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "sbyte":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "short":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "int":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "long":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "float":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"0.1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "double":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"0.1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "decimal":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <NumericUpDown Increment=\"0.1\" Value=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "string":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine($"            <TextBox Text=\"{{Binding {property.GetName()}}}\"/>");
                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "DateTime":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <DatePicker SelectedDate=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "CalendarDatePicker":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <DatePicker SelectedDate=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
            case "TimeSpan":
            {
                stringBuilder.AppendLine("        <StackPanel>");

                stringBuilder.AppendLine(
                    $"            <TextBlock Text=\"{{StaticResource Lang.{property.GetName()}}}\"/>");

                stringBuilder.AppendLine(
                    $"            <TimePicker SelectedTime=\"{{Binding {property.GetName()}}}\"/>");

                stringBuilder.AppendLine("        </StackPanel>");

                return;
            }
        }
    }
}