using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Inanna.SourceGenerator;

[Generator]
public class EditNotifyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
           .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax classDeclaration
                 && classDeclaration.AttributeLists
                       .SelectMany(x => x.Attributes)
                       .Any(x => x.Name.ToString() == "EditNotify"),
                static (context, _) => (ClassDeclarationSyntax)context.Node)
           .Collect();

        var combine = context.CompilationProvider.Combine(provider);

        context.RegisterSourceOutput(combine, (spc, obj) =>
        {
            var (compilation, list) = obj;

            foreach (var source in list)
            {
                var properties = source.Members.OfType<PropertyDeclarationSyntax>().ToArray().AsSpan();
                var stringBuilder = new StringBuilder();
                stringBuilder.AppendLine("// <auto-generated />");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine("#nullable enable");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine($"namespace {source.GetNamespace()};");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine($"public partial class {source.GetName()}");
                stringBuilder.AppendLine("{");

                stringBuilder.AppendLine(
                    $"    protected override void OnPropertyChanged(global::{TypeNames.PropertyChangedEventArgs} e)");

                stringBuilder.AppendLine("    {");
                stringBuilder.AppendLine("            base.OnPropertyChanged(e);");
                stringBuilder.AppendLine("        switch (e.PropertyName)");
                stringBuilder.AppendLine("        {");
                var enumProperties = new List<PropertyDeclarationSyntax>();
                var editProperties = new List<PropertyDeclarationSyntax>();

                foreach (var property in properties)
                {
                    if (!property.AttributeLists.Any())
                    {
                        continue;
                    }

                    if (property.GetName().StartsWith("IsEdit"))
                    {
                        continue;
                    }

                    editProperties.Add(property);
                    stringBuilder.AppendLine($"            case nameof(IsEdit{property.GetName()}):");
                    stringBuilder.AppendLine("            {");
                    stringBuilder.AppendLine("                OnPropertyChanged(nameof(IsEdit));");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("                break;");
                    stringBuilder.AppendLine("            }");
                    stringBuilder.AppendLine($"            case nameof({property.GetName()}):");
                    stringBuilder.AppendLine("            {");
                    stringBuilder.AppendLine($"                IsEdit{property.GetName()} = true;");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("                break;");
                    stringBuilder.AppendLine("            }");
                    var semanticModel = compilation.GetSemanticModel(property.Type.SyntaxTree);
                    var symbolInfo = semanticModel.GetSymbolInfo(property.Type);
                    var symbol = symbolInfo.Symbol;

                    if (symbol is INamedTypeSymbol { TypeKind: TypeKind.Enum, })
                    {
                        enumProperties.Add(property);
                    }
                }

                stringBuilder.AppendLine();
                stringBuilder.AppendLine("        }");
                stringBuilder.AppendLine("    }");

                stringBuilder.AppendLine(
                    $"protected void ResetEdit() {{{string.Join(string.Empty, editProperties.Select(x => $"IsEdit{x.GetName()} = false;"))};}}");

                stringBuilder.AppendLine(
                    $"public bool IsEdit => {string.Join(" || ", editProperties.Select(x => $"IsEdit{x.GetName()}"))};");

                stringBuilder.AppendLine("}");
                var text = stringBuilder.ToString();
                spc.AddSource($"EditNotify.{source.GetName()}.g.cs", text);
            }
        });
    }
}