using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Inanna.SourceGenerator;

[Generator]
public class ViewLocatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
           .CreateSyntaxProvider(
                static (node, _) => node is AttributeSyntax attribute && attribute.Name.ToString() == "ViewPair",
                static (context, _) => (AttributeSyntax)context.Node)
           .Collect();

        var combined = context.CompilationProvider.Combine(provider);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var (compilation, list) = pair;

            if (list.Length == 0)
            {
                return;
            }

            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// <auto-generated />");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("#nullable enable");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("using System.Collections.Frozen;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"namespace {compilation.AssemblyName}.SourceGenerator;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"public static class {compilation.AssemblyName}ViewLocator");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    public static readonly global::{TypeNames.FrozenDictionary}<global::{TypeNames.Type}, global::{TypeNames.Func}<global::{TypeNames.Control}>> Builders;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"    static {compilation.AssemblyName}ViewLocator()");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine($"        var dictionary = new global::{TypeNames.Dictionary}<global::{TypeNames.Type}, global::{TypeNames.Func}<global::{TypeNames.Control}>>");
            stringBuilder.AppendLine("        {");
            
            foreach (var source in list)
            {
                var viewType = source.GetAttributeValueType(0);
                var viewModelType = source.GetAttributeValueType(1);
                stringBuilder.AppendLine($"            {{ typeof(global::{viewModelType.GetFullName(compilation)}) , () => new global::{viewType.GetFullName(compilation)}() }},");
            }

            stringBuilder.AppendLine("        };");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("    Builders = dictionary.ToFrozenDictionary();");
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");
            var text = stringBuilder.ToString();
            spc.AddSource("ViewLocator.g.cs", text);
        });
    }
}